CREATE TABLE Person (
                        id INT primary key GENERATED BY DEFAULT AS IDENTITY,
                        name VARCHAR(100) NOT NULL UNIQUE,
                        birth_year int NOT NULL
);
CREATE TABLE Book (
                      id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      person_id INT REFERENCES person(id) ON DELETE SET NULL,
                      name VARCHAR(100) NOT NULL,
                      author VARCHAR(100) NOT NULL,
                      year INT NOT NULL
);
-- 1. Добавляем людей (Person)
INSERT INTO Person (name, birth_year) VALUES
                                          ('Иванов Иван Иванович', 1990),
                                          ('Петров Петр Петрович', 1985),
                                          ('Сидорова Анна Сергеевна', 1995);

-- 2. Добавляем книги (Book)
INSERT INTO Book (person_id, name, author, year) VALUES
                                                     (1, 'Война и мир', 'Лев Толстой', 1869),             -- Книга Иванова
                                                     (2, 'Преступление и наказание', 'Ф. Достоевский', 1866), -- Книга Петрова
                                                     (NULL, 'Три товарища', 'Эрих Мария Ремарк', 1936),   -- Книга Ремарка БЕЗ владельца (свободна)
                                                     (1, 'Капитанская дочка', 'А. Пушкин', 1836),          -- Еще одна книга Иванова
                                                     (NULL, 'Мастер и Маргарита', 'М. Булгаков', 1967);       -- Книга Сидоровой
